spring:
  application:
    name: gateway
server:
  port: 9018

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9020/eureka

zuul:
  routes:
    leads:
      path: /leads/**
      url: http://localhost:8080/hozon
      #保留请求header信息
      sensitive-headers:
      custom-sensitive-headers: true
    hozon:
      path: /hozon/**
      url: http://localhost:8080/hozon
      #保留请求header信息
      sensitive-headers:
      custom-sensitive-headers: true
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
